
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 27 01:43:18 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RARROW = 40;
  public static final int DIVIDE = 25;
  public static final int MAP = 22;
  public static final int LMED = 38;
  public static final int CONST = 14;
  public static final int NOTEQUAL = 28;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 21;
  public static final int MINUS = 23;
  public static final int RPAREN = 7;
  public static final int GRE = 29;
  public static final int AND = 33;
  public static final int OR = 34;
  public static final int COMMA = 8;
  public static final int CLASS = 15;
  public static final int INC = 35;
  public static final int PLUS = 11;
  public static final int MULTIPLY = 24;
  public static final int IF = 49;
  public static final int DOT = 41;
  public static final int LE = 31;
  public static final int TARABA = 42;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RMED = 39;
  public static final int EQUAL = 12;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int STEPEN = 44;
  public static final int NUMBER = 45;
  public static final int IDENT = 48;
  public static final int BREAK = 17;
  public static final int VOID = 13;
  public static final int MODULE = 26;
  public static final int COLON = 37;
  public static final int ELSE = 50;
  public static final int LBRACE = 3;
  public static final int SKIP = 43;
  public static final int READ = 20;
  public static final int CHARCONST = 46;
  public static final int WHILE = 18;
  public static final int DOUBLEEQUAL = 27;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 47;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int LEQ = 32;
  public static final int GREEQ = 30;
  public static final int DEC = 36;
  public static final int PRINT = 9;
}

