
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
	public static final int EOF = 0;
	public static final int error = 1;
	public static final int PROG = 2;
	public static final int LBRACE = 3;
	public static final int RBRACE = 4;
	public static final int SEMI = 5;
	public static final int LPAREN = 6;
	public static final int RPAREN = 7;
	public static final int COMMA = 8;
	public static final int PRINT = 9;
	public static final int RETURN = 10;
	public static final int PLUS = 11;
	public static final int EQUAL = 12;
	public static final int VOID = 13;
	public static final int NUMBER = 14;
	public static final int IDENT = 15;
	public static final int IF = 16;
	public static final int ELSE = 17;
	//JA
	public static final int BREAK = 18;
	public static final int CLASS = 19;
	public static final int CONST = 20;
	public static final int WHILE = 21;
	public static final int NEW = 22;
	public static final int READ = 23;
	public static final int EXTENDS = 24;
	public static final int CONTINUE = 25;
	public static final int MAP = 26;
	public static final int CHARCONST = 27;
	public static final int BOOLCONST = 28;
	public static final int MINUS = 29;
	public static final int MULTIPLY = 30;
	public static final int DIVIDE = 31;
	public static final int MODULE = 32;
	public static final int DOUBLEEQUAL = 33;
	public static final int NOTEQUAL = 34;
	public static final int GRE = 35;
	public static final int GREEQ = 36;
	public static final int LE = 37;
	public static final int LEQ = 38;
	public static final int AND = 39;
	public static final int OR = 40;
	public static final int INC = 41;
	public static final int DEC = 42;
	public static final int COLON = 43;
	public static final int LMED = 44;
	public static final int RMED = 45;
	public static final int RARROW = 46;
	public static final int DOT = 47;
	
}

